### ISSUE TITLE
 cannot use helloWorld (type func(http.ResponseWriter, *http.Request)) as type http.Handler

### ISSUE THREAD

**Issue by tablecell** [ArturoVM/min#1]
```
import (
    "fmt"
    "net/http"

    "github.com/julienschmidt/httprouter"

    "github.com/arturovm/min"
    "github.com/arturovm/min/adapter"
)

func main() {
    a := &adapter.Httprouter{Router: httprouter.New()}
    m := min.New(a)

    m.Get("/", helloWorld)

    http.ListenAndServe(":8080", m)
}

func helloWorld(w http.ResponseWriter, r *http.Request) {
    fmt.Fprintln(w, "hello world!")
}
```
main.go:16:11: cannot use helloWorld (type func(http.ResponseWriter, *http.Request)) as type http.Handler in argument to m.Group.Get:
      func(http.ResponseWriter, *http.Request) does not implement http.Handler (missing ServeHTTP method)

**Comment by arturovm** [comment]
@tablecell Hello! Sorry for the delay. Thank you very much for bringing this to my attention. I've fixed the README.
